### ISSUE TITLE
batchified ci_sdr loss?

### ISSUE THREAD

**Issue by kamo-naoyuki** [fgnt/ci_sdr#1]
Thank you for releasing this tool!

`ci_sdr_loss()` seems not to support batchified computation. Will you implement it?

```
est: batch x source x samples
ref: batch x source x samples
```

**Comment by boeddeker** [comment]
Until yet, I haven't optimized the code to support batch dimensions.
Inside the source code is also a loop over the sources. 

I will add a PR and add support for a batch dimension.
For `compute_permutation` I am not sure yet, if it will be a loop over the batch dimension or a torch operation.

**Comment by boeddeker** [comment]
In #2 I added now batch support and the possibility to work with large number of speakers (i.e. Hungarian style PIT realization).

**Comment by kamo-naoyuki** [comment]
Oh, thanks for quick supporting!
